### ISSUE TITLE
Fair comparison woth PostCSS

### ISSUE THREAD

**Issue by ai** [stylecow/stylecow#7]
I’ve always liked your clean and good API. And event-based plugins are really awesome idea.

But Stylecow vs. PostCSS comparison on [Stylecow](http://stylecow.github.io/) page is not correct.

1. “Too many plugins, too many verbose”. This is why we have a plugins pack. You just add `cssnext` pack and CSS4 just work. So this part if not true.
2. “No centralized browser support”. It is not true, because most of PostCSS plugins support [Browserslist](https://github.com/ai/browserslist) config file. You miss it because you looked at separated plugins and not at [cssnext](https://github.com/cssnext/cssnext#nodejs-options) plugin pack.
3. Event-based plugins is really faster. But difference is much lower, because your benchmark is not correct.
    1. Your CSS example is not representative, because you test only CSS4 feature. But real CSS will contains many normal nodes like comments, declaration, etc. So in [PostCSS benchark](https://github.com/postcss/postcss/blob/master/benchmark/general.js) I parse a Bootstrap before all mixins/CSS4 features to make CSS example more real.
    2. `autoprefixer-core` and `stylecow-plugin-prefixes` have not same functionality. Autoprefixer has many look backs to not double already written prefixes in legacy code. Also Autoprefixer try to remove old prefixes and detects hacks.

**Comment by ai** [comment]
[My benchmark](https://github.com/postcss/postcss/blob/master/benchmark/general.js) with more real (of course, it created to compare preprocessors features, so on CSS4 features Stylecow will have better results because it will use more plugins):

```
PostCSS:   36 ms
Rework:    77 ms   (2.1 times slower)
libsass:   136 ms  (3.8 times slower)
Less:      160 ms  (4.4 times slower)
Stylus:    167 ms  (4.6 times slower)
Stylecow:  208 ms  (5.7 times slower)
Ruby Sass: 1084 ms (30.1 times slower)
```

**Comment by MoOx** [comment]
As the creator of cssnext, I have to admit that the comparison is unfair. You should compare stylecow vs cssnext, not postcss which is just an engine.

For benchmarks, you should also compare what is comparable so cssnext vs stylecow.

**Comment by oscarotero** [comment]
Sorry, my intention is not cheating. I've compared postscss directly because cssnext is a collection of plugins for postcss and I wanted to be sure to compare the same features.
The benchmark result depends of the plugins you choose. Some plugins are faster in postcss and some in stylecow, so I've choosen the most common features. But i'm willing to change the test to make it more real-world. :smile:

**Comment by ai** [comment]
@oscarotero in Stylecow page you said, that Stylecow is 6 times faster, because of PostCSS slower API. But it not true. Your benchmark has this result mostly because Autoprefixer is much smarter, that `stylecow-plugin-prefixes`. So this is why thi block of code is not fair.

So main problem is in text on Stylecow page. Because most parts is not true.

**Comment by ai** [comment]
In Autoprefixer 5.2 I can add a `fast` option to have similar logic as `stylecow-plugin-prefixes`. But you can make your bencchmark more real if you will add some simple CSS3 code. In real examples, postprocessors change minor part of CSS. Most CSS content is just a simple declaration without some magic for processors.

And this is why in PostCSS we focused on parser perfomance, instead of plugin perfomance. Because plugin will be accepted only to few nodes. Most nodes will be a simple and borring CSS.

**Comment by oscarotero** [comment]
I've replaced the css used in the benchmark for a more real code (in fact, it's a code from a real project). I've removed some `@import` rules pointing to bower components and a lot of parts using variables because cssnext does not support variables outside `:root`, but I think this can be considerated an enought "real" example.

I've replaced also all plugins of postcss for cssnext. The results in my computer are:
```
stylecow x 5.99 ops/sec ±4.84% (20 runs sampled)
cssnext x 6.55 ops/sec ±3.84% (21 runs sampled)
Fastest is cssnext

stylecow x 6.11 ops/sec ±3.93% (20 runs sampled)
cssnext x 6.61 ops/sec ±4.79% (21 runs sampled)
Fastest is cssnext

stylecow x 6.20 ops/sec ±4.55% (20 runs sampled)
cssnext x 6.62 ops/sec ±3.54% (21 runs sampled)
Fastest is cssnext
```
I admit that cssnext is a bit faster than stylecow but the diference is not as big (7% aprox.). Anyway,  these benchmarks are fine to optimice the libraries but the comparison never will be fair, because each library does different things (autoprefixer is smarter than stylecow-prefixes, but stylecow-parser is smarter than postcss parser). Depending of the code and the plugin used, one library can be faster than other. So, I will remove this part of the stylecow page.

:smile:

**Comment by ai** [comment]
Don't forget about browsers support data. Browserslist is awesome because it used not only in Autoprefixer and cssnext, but in non-CSS tools like Autopolyfiller.

Maybe you want to support it too? It will allow to set browsers not only by versions, but also by queries like `> 5%`.

**Comment by oscarotero** [comment]
Yes, I didn't know it but it's a useful library.
